version: '3.4'

services:
  heyhowsitgoingbot:
    image: heyhowsitgoingbot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    external: false